version: '3.8'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    command: node server.js

  nginx:
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - frontend
      - backend
